name: keras
channels:
  - conda-forge
  - damianavila82
dependencies:
  - python==3.6
  - ipython
  - jupyter
  - jupyter_contrib_nbextensions
  - tensorflow==1.9
  - keras>=2.2
  - numpy
  - matplotlib
  - pip:
    - rise
